name: Tag and Push

on:
  push:
    branches:
      - main
      - hotfix/**
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  tag-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'

      - name: Create Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "v1.0.0" -m "Release 1.0.0"
          git push origin "v1.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
