name: Versioning

on:
  push:
    branches:
      - main
      - hotfix/**
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: 1.0.0
          release_name: Release 1.0.0
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
