name: Create and Push Tag

on:
  push:
    branches:
      - main

jobs:
  tag-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # This permission is needed to push tags

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched for tagging

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Delete existing tag if it exists
        run: |
          if git rev-parse "v1.0.0" >/dev/null 2>&1; then
            echo "Tag v1.0.0 already exists. Deleting it."
            git tag -d "v1.0.0"
            git push origin --delete "v1.0.0"
          else
            echo "Tag v1.0.0 does not exist. No action needed."
          fi

      - name: Create and push new tag
        run: |
          git tag -a "v1.0.0" -m "Release 1.0.0"
          git push origin "v1.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
