name: Create and Push Tag

on:
  push:
    branches:
      - main

jobs:
  tag-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # This permission is needed to push tags

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched for tagging

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Update this to your .NET version if needed

      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool

      - name: Generate version number
        id: version
        run: |
          VERSION=$(dotnet-gitversion /showvariable SemVer)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create and push tag
        run: |
          if git rev-parse "$VERSION" >/dev/null 2>&1; then
            echo "Tag $VERSION already exists. Skipping tag creation."
          else
            git tag -a "$VERSION" -m "Release $VERSION"
            git push origin "$VERSION"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
