name: Versioning

on:
  push:
    branches:
      - main
      - hotfix/**
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    container:
      image: gittools/gitversion:5.6.11  # Update to the specific version if available

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine version
        run: gitversion /output json /showvariable FullSemVer
        id: gitversion

      - name: Create GitHub Release
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/hotfix/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.gitversion.outputs.FullSemVer }}
          release_name: Release ${{ steps.gitversion.outputs.FullSemVer }}
          draft: false
          prerelease: false
