name: Versioning

on:
  push:
    branches:
      - main
      - hotfix/**
  tags:
    - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'

      - name: Install GitVersion
        run: |
          dotnet tool install --global GitVersion.Tool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Determine Version
        id: gitversion
        run: |
          dotnet-gitversion /output json /showvariable FullSemVer
        continue-on-error: true

      - name: Create GitHub Release
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/hotfix/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.gitversion.outputs.FullSemVer }}
          release_name: Release ${{ steps.gitversion.outputs.FullSemVer }}
          draft: false
          prerelease: false
