name: Versioning

on:
  push:
    branches:
      - main
      - hotfix/**
  pull_request:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'

      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool

      - name: Determine version
        run: gitversion /output json /showvariable FullSemVer
        id: gitversion

      - name: Create GitHub Release
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/hotfix/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.gitversion.outputs.FullSemVer }}
          release_name: Release ${{ steps.gitversion.outputs.FullSemVer }}
          draft: false
          prerelease: false
